spring:
  application:
    name: notification-service

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/notification_db}
    username: ${DATABASE_USERNAME:noti_user}
    password: ${DATABASE_PASSWORD:noti_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2
          max-interval: 10000

server:
  port: ${SERVER_PORT:8083}
  compression:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

notification:
  mail:
    mock: ${NOTIFICATION_MAIL_MOCK:true}
  from:
    email: noreply@trabajogrado.com
    name: "Sistema Trabajo de Grado"
  retry:
    max-attempts: 3
    delay: 5000

rabbitmq:
  queues:
    notification: notification.queue
    email: notification.email.queue
  exchanges:
    notification: notification.exchange
  routing-keys:
    notification: notification.routing.key
    email: notification.email.routing.key

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    root: INFO
    co.unicauca.microservice: DEBUG
    org.springframework.web: INFO
    org.springframework.amqp: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"