version: '3.8'

services:
  # Base de datos PostgreSQL para submission service
  submission-postgres:
    image: postgres:15-alpine
    container_name: submission-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: submissiondb
      POSTGRES_USER: submission_user
      POSTGRES_PASSWORD: submission_pass
    ports:
      - "5435:5432"
    volumes:
      - submission-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U submission_user -d submissiondb"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - submission-network

  # RabbitMQ para desarrollo local
  rabbitmq-local:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq-local
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq-local-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - submission-network

  # Submission Service
  submission-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: submission-service-local
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8082
      - JWT_SECRET=test-secret-key-for-jwt-validation-minimum-256-bits-long
      - SPRING_DATASOURCE_URL=jdbc:postgresql://submission-postgres:5432/submissiondb
      - SPRING_DATASOURCE_USERNAME=submission_user
      - SPRING_DATASOURCE_PASSWORD=submission_pass
      - SPRING_RABBITMQ_HOST=rabbitmq-local
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - FILE_STORAGE_PATH=/app/uploads
    volumes:
      - submission-uploads:/app/uploads
    depends_on:
      submission-postgres:
        condition: service_healthy
      rabbitmq-local:
        condition: service_healthy
    networks:
      - submission-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  submission-network:
    driver: bridge

volumes:
  submission-db-data:
    driver: local
  rabbitmq-local-data:
    driver: local
  submission-uploads:
    driver: local