package co.unicauca.comunicacionmicroservicios.domain.model;

public enum enumEstadoProyecto {
    FORMATO_A_DILIGENCIADO,   // Inicial
    PRESENTADO_AL_COORDINADOR,
    EN_EVALUACION_COMITE,
    CORRECCIONES_COMITE,
    ACEPTADO_POR_COMITE,
    RECHAZADO_POR_COMITE,
    ESCRIBIENDO_ANTEPROYECTO,
    PRESENTADO_JEFATURA,
    APROBADO_CONSEJO,
    EN_DESARROLLO,
    FINALIZADO_MONOGRAFIA,
    RECHAZADO_DEFINITIVO
}

